### ISSUE TITLE
discussion of requirements

### ISSUE THREAD

**Issue by OlgaVasilenko** [ViktorKos/diver_accelerator#2]
изучить требования к пояснительной записке диплома

**Comment by ViktorKos** [comment]
[

[diplom sample step.docx](https://github.com/ViktorKos/diver_accelerator/files/10529529/diplom.sample.step.docx)

]

для примера записки

презентация


[eCommerce Android.pptx](https://github.com/ViktorKos/diver_accelerator/files/10529534/eCommerce.Android.pptx)

**Comment by ViktorKos** [comment]
@OlgaVasilenko  нужен драфт пояснительной по проекту, согласно требований академии и примера

**Comment by OlgaVasilenko** [comment]
@ViktorKos draft пояснительной записки подготовлен[link](https://docs.google.com/document/d/1fIyrob6rvOE60--rVYpoKGJECKmfdXt7/edit)
