### ISSUE TITLE
Create Mocup for project

### ISSUE THREAD

**Issue by OlgaVasilenko** [ViktorKos/diver_accelerator#30]
![Image](https://user-images.githubusercontent.com/22616289/218793886-3e92364a-6f97-4ab3-939d-17ff54344793.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/219955665-16865154-3954-419a-bf75-d9f8b0c5174d.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/219955702-a01a8e32-ff33-4158-aa16-3b87abc8db5c.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/219955762-3a2afb62-f0bf-470f-9690-32cb3fee4b97.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/219955812-1f5e8150-6c09-489b-b8a3-f820e2740bd8.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/219955854-4a7ccec6-5e78-4b0c-a7b2-e39871a23418.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/219955891-8683cedc-8605-4003-a48b-aeeb701afb5b.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/219955933-3ce4b36e-5387-4b08-aab7-1431822f0190.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/219955966-b23bcca6-8263-4f51-95f6-29b10ed42187.png)

**Comment by ViktorKos** [comment]
navigation bar has been done
