### ISSUE TITLE
Регрессивное тестирование админ. панели User

### ISSUE THREAD

**Issue by OlgaVasilenko** [ViktorKos/diver_accelerator#33]
не работает admin/user/update/ change password  не реализовна страница

This application has no explicit mapping for /error, so you are seeing this as a fallback.

There was an unexpected error (type=Not Found, status=404).
/WEB-INF/admin/forms/form_user_password.jsp

**Comment by OlgaVasilenko** [comment]
реализовать интерфейс смены пароля.

**Comment by ViktorKos** [comment]
![Image](https://user-images.githubusercontent.com/22616289/220173879-140a50a9-abc3-4405-b136-406985876675.png)

**Comment by ViktorKos** [comment]
тестирование проведено
