### ISSUE TITLE
Visitors CRUD Mockup

### ISSUE THREAD

**Issue by OlgaVasilenko** [ViktorKos/diver_accelerator#36]

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/220432059-2b89553d-54a8-49bd-8fb5-9bb59f9c4e84.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/220739275-87a736d7-6fe6-495f-a3fc-e7e7cbe2d8c2.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/220739320-85ab1259-8a0b-42f8-81ce-56d9ce8ee690.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/220745588-74a15fc7-387d-49f4-b948-7e6f34e610d4.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/220745807-57f9525c-9c34-4fe3-9173-c75bedfcf8ea.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/220755296-0d063e6e-56c6-4b19-be31-0b2e6f5a2f8c.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/220755484-aee51e00-c1dd-4b8b-82cc-627ed160b5dd.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/220755563-1e0f0db0-ce5b-427c-81fd-c0c66f89d513.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/221011700-41c495f3-207b-494f-9765-1aef181788c1.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/221014966-3ee30475-cd0e-4955-81bb-d635e7f5baa2.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/221017966-d09b5299-fa53-41e9-845c-0ef9834827aa.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/221019670-364e96dd-348d-4c7a-9a16-7c8d103d6b9e.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/221021336-148156b6-d24a-4fdc-ade1-0dae0239c476.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/221022768-545781a1-d785-463d-a125-9d9f2df84080.png)

**Comment by ViktorKos** [comment]
done
