### ISSUE TITLE
instructor CRUD mockup

### ISSUE THREAD

**Issue by OlgaVasilenko** [ViktorKos/diver_accelerator#43]
![Image](https://user-images.githubusercontent.com/118020941/222919574-3fd7e5a5-d0a3-4002-b72f-350a23b6d803.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/222920343-d0b14356-fac0-4163-a069-f1cb131a2434.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/222920637-f1a2d104-60a9-4c2c-a776-60a47baac8d1.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/222921349-7992a2ac-cc00-4e9e-baff-ed23c2dc1154.png)

**Comment by OlgaVasilenko** [comment]
![Image](https://user-images.githubusercontent.com/118020941/222921358-cb24e667-af93-4b95-9a36-d4e5816f3ed7.png)

**Comment by ViktorKos** [comment]
pls add 2 mock-ups   add and ups schedule @OlgaVasilenko

**Comment by ViktorKos** [comment]
done @OlgaVasilenko
